apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  flux_kustomization_default_interval: "1h0m0s"
  flux_kustomization_default_retry_interval: "10m0s"
  longhorn_namespace: "longhorn-system"
  longhorn_recurring_backup_cron: "15 3 * * *"
  longhorn_recurring_backup_retain: "14"
  longhorn_recurring_full_backup_interval: "7"
