# All ${...} keys apps/forgejo-runner consumes, with sane defaults.
apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
data:
  forgejo_namespace: "forgejo"
  forgejo_runner_suspend: "true"
  forgejo_runner_image: "code.forgejo.org/forgejo/runner:6.3.1"
  forgejo_runner_dind_image: "docker.io/library/docker:27.5.1-dind"
  forgejo_runner_name: "k8s-homelab"
  forgejo_runner_instance_url: "https://git.h4xx.io"
  forgejo_runner_token_secret_name: "forgejo-runner-token"
  forgejo_runner_state_size: "1Gi"
  forgejo_runner_dind_cache_size: "30Gi"
  forgejo_runner_dind_memory_limit: "8Gi"
  forgejo_runner_storage_class_name: "longhorn-ssd-rwo-1r"
