apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  obsidian_livesync_suspend: "true"
  obsidian_couchdb_image: "docker.io/library/couchdb:3.5.2"
  obsidian_storage_class: "longhorn-ssd-rwo-2r"
  obsidian_data_size: "10Gi"
  obsidian_secret_name: "couchdb-admin"
