apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repo.yaml
  - grafana-helm-release.yaml
  - k8s-monitoring-helm-release.yaml
  - loki-helm-release.yaml
  - mimir-helm-release.yaml
  - tempo-helm-release.yaml
  - ingress-ingest.yaml
  - rules-sync
  - dashboards
