apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repo.yaml
  - grafana-helm-release.yaml
  - kube-state-metrics-helm-release.yaml
  - node-exporter-helm-release.yaml
  - loki-helm-release.yaml
  - mimir-helm-release.yaml
  - tempo-helm-release.yaml
  - alloy-helm-release.yaml
  - ingress-ingest.yaml
  - dashboards
