apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m0s
  timeout: 15m0s
  chart:
    spec:
      chart: loki
      version: 6.52.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 10m0s
  valuesFrom:
    - kind: Secret
      name: loki-values
      valuesKey: values.yaml
  values:
    fullnameOverride: loki
    deploymentMode: Distributed
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: ${loki_replication_factor}
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage:
        type: s3
        bucketNames:
          chunks: ${monitoring_loki_bucket}
          ruler: ${monitoring_loki_bucket}
          admin: ${monitoring_loki_bucket}
        s3:
          endpoint: ${monitoring_s3_endpoint}
          region: ${monitoring_s3_region}
          s3ForcePathStyle: ${monitoring_s3_force_path_style}
          insecure: ${monitoring_s3_insecure}
    gateway:
      replicas: ${loki_read_replicas}
    distributor:
      replicas: ${loki_write_replicas}
    ingester:
      replicas: ${loki_write_replicas}
    querier:
      replicas: ${loki_read_replicas}
    queryFrontend:
      replicas: ${loki_read_replicas}
    queryScheduler:
      replicas: ${loki_read_replicas}
    indexGateway:
      replicas: ${loki_backend_replicas}
    compactor:
      replicas: ${loki_backend_replicas}
    ruler:
      replicas: ${loki_backend_replicas}
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
    minio:
      enabled: false
