apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 10m0s
  timeout: 15m0s
  chart:
    spec:
      chart: mimir-distributed
      version: 6.0.5
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 10m0s
  valuesFrom:
    - kind: Secret
      name: mimir-values
      valuesKey: values.yaml
  values:
    fullnameOverride: mimir
    mimir:
      structuredConfig:
        common:
          storage:
            backend: s3
            s3:
              endpoint: ${monitoring_s3_endpoint}
              region: ${monitoring_s3_region}
              bucket_name: ${monitoring_mimir_blocks_bucket}
              insecure: ${monitoring_s3_insecure}
        blocks_storage:
          backend: s3
          s3:
            endpoint: ${monitoring_s3_endpoint}
            region: ${monitoring_s3_region}
            bucket_name: ${monitoring_mimir_blocks_bucket}
            insecure: ${monitoring_s3_insecure}
        alertmanager_storage:
          backend: s3
          s3:
            endpoint: ${monitoring_s3_endpoint}
            region: ${monitoring_s3_region}
            bucket_name: ${monitoring_mimir_alertmanager_bucket}
            insecure: ${monitoring_s3_insecure}
        ruler_storage:
          backend: s3
          s3:
            endpoint: ${monitoring_s3_endpoint}
            region: ${monitoring_s3_region}
            bucket_name: ${monitoring_mimir_ruler_bucket}
            insecure: ${monitoring_s3_insecure}
    minio:
      enabled: false
