apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 10m0s
  timeout: 15m0s
  chart:
    spec:
      chart: tempo-distributed
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: monitoring
      interval: 10m0s
  valuesFrom:
    - kind: Secret
      name: tempo-values
      valuesKey: values.yaml
  values:
    fullnameOverride: tempo
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo-traces
          endpoint: tempo-minio.monitoring.svc.cluster.local:9000
          region: ${monitoring_s3_region}
          insecure: true
          forcepathstyle: true
    minio:
      enabled: true
      buckets:
        - name: tempo-traces
          policy: none
          purge: false
      persistence:
        size: ${monitoring_minio_size}
        storageClass: ${monitoring_minio_storage_class_name}
