apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twofauth-data
  namespace: twofauth
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${default_sts_storage_class_name}
  resources:
    requests:
      storage: 1Gi
