apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 10m0s
  timeout: 10m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: media
      interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/bazarr
              tag: 1.5.5
            env:
              TZ: ${media_timezone}
              PUID: ${media_puid}
              PGID: ${media_pgid}
            resources:
              requests:
                cpu: 100m
                memory: 192Mi
              limits:
                cpu: 1000m
                memory: 512Mi
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: ${default_cluster_issuer}
          external-dns.alpha.kubernetes.io/target: ${cloudflare_tunnel_hostname}
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia-forwardauth@kubernetescrd
        hosts:
          - host: bazarr${public_host_suffix}.${delegating_domain}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: bazarr-tls
            hosts:
              - bazarr${public_host_suffix}.${delegating_domain}
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: ${arr_config_storage_class_name}
        size: ${arr_config_size}
        globalMounts:
          - path: /config
      media:
        enabled: true
        existingClaim: arr-media
        globalMounts:
          - path: /media
