apiVersion: v1
kind: ConfigMap
metadata:
  name: buildarr-config
  namespace: media
data:
  buildarr.yml: |-
    ---
    includes:
      - buildarr-secret.yml

    buildarr:
      watch_config: false
      update_days:
        - monday
        - tuesday
        - wednesday
        - thursday
        - friday
        - saturday
        - sunday
      update_times:
        - "03:00"

    sonarr:
      hostname: sonarr
      port: 8989
      protocol: http

    radarr:
      hostname: radarr
      port: 7878
      protocol: http
