apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: buildarr
  namespace: media
spec:
  interval: 10m0s
  timeout: 10m0s
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: media
      interval: 10m0s
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "0 3 * * *"
          successfulJobsHistory: 1
          failedJobsHistory: 3
        containers:
          main:
            image:
              repository: callum027/buildarr
              tag: 0.7.8
            command:
              - buildarr
            args:
              - run
            workingDir: /config
            env:
              PUID: ${media_puid}
              PGID: ${media_pgid}
    persistence:
      config:
        enabled: true
        type: configMap
        name: buildarr-config
        globalMounts:
          - path: /config/buildarr.yml
            subPath: buildarr.yml
      secret:
        enabled: true
        type: secret
        name: buildarr-secret
        globalMounts:
          - path: /config/buildarr-secret.yml
            subPath: buildarr-secret.yml
