apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - helm-repo.yaml
  - pvc-media.yaml
  - jellyfin-transcode-cache.yaml
  - qbittorrent-config.yaml
  - qbittorrent.yaml
  - qbittorrent-network-policy.yaml
  - qbittorrent-policy.yaml
  - qbit-manage-config.yaml
  - qbit-manage.yaml
  - metube-presets.yaml
  - metube.yaml
  - jellyfin-music-refresh.yaml
  - prowlarr.yaml
  - prowlarr-bootstrap-config.yaml
  - prowlarr-bootstrap.yaml
  - arr-api-key-init.yaml
  - sonarr.yaml
  - pvc-radarr-config-rbd.yaml
  - radarr.yaml
  - lidarr.yaml
  - readarr.yaml
  - bazarr.yaml
  - jellyseerr.yaml
  - jellyseerr-config-sync.yaml
  - jellyseerr-admin-sync.yaml
  - jellyfin.yaml
  - jellyfin-admin-sync.yaml
  - jellyfin-metrics-ingressroute.yaml
  - jellyfin-bootstrap-config.yaml
  - jellyfin-bootstrap.yaml
  - jellyfin-branding.yaml
  - flaresolverr.yaml
  - profilarr.yaml
