apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - helm-repo.yaml
  - pvc-downloads.yaml
  - pvc-media.yaml
  - qbittorrent-config.yaml
  - qbittorrent.yaml
  - prowlarr.yaml
  - arr-api-key-init.yaml
  - sonarr.yaml
  - radarr.yaml
  - lidarr.yaml
  - readarr.yaml
  - bazarr.yaml
  - jellyseerr.yaml
  - jellyfin.yaml
  - jellyfin-branding.yaml
  - flaresolverr.yaml
  - buildarr-config.yaml
  - buildarr.yaml
  - recyclarr-config.yaml
  - recyclarr.yaml
