apiVersion: v1
kind: ConfigMap
metadata:
  name: metube-presets
  namespace: media
data:
  presets.json: |-
    {
      "embed-metadata": {
        "writethumbnail": true,
        "postprocessors": [
          { "key": "FFmpegMetadata" },
          { "key": "EmbedThumbnail" }
        ]
      },
      "normalize-audio": {
        "postprocessor_args": {
          "ffmpeg": ["-af", "loudnorm=I=-16:TP=-1.5:LRA=11"]
        }
      }
    }
