apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${arr_media_size}
  storageClassName: ${arr_media_storage_class_name}
