apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    recurring-job-group.longhorn.io/default: disabled
  name: arr-media-v2
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${arr_media_size}
  storageClassName: ${arr_media_storage_class_name}
