apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-rbd
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${arr_config_size}
  storageClassName: ${default_sts_storage_class_name}
