apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-downloads
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${arr_downloads_size}
  storageClassName: ${arr_downloads_storage_class_name}
