apiVersion: v1
kind: ConfigMap
metadata:
  name: qbit-manage-config
  namespace: media
data:
  config.yml: |-
    commands:
      dry_run: ${qbit_manage_dry_run}
      recheck: false
      cat_update: false
      tag_update: true
      rem_unregistered: false
      tag_tracker_error: true
      rem_orphaned: false
      tag_nohardlinks: false
      share_limits: false
      skip_qb_version_check: false
      skip_cleanup: true

    qbt:
      host: "qbittorrent:8080"
      user:
      pass:

    settings:
      force_auto_tmm: false
      tracker_error_tag: issue
      nohardlinks_tag: noHL
      stalled_tag: stalledDL
      tag_stalled_torrents: true
      disable_qbt_default_share_limits: false

    directory:
      root_dir: "/media/downloads"
      recycle_bin: "/media/downloads/.RecycleBin"
      orphaned_dir: "/media/downloads/orphaned_data"

    cat:
      Uncategorized: "/media/downloads/other"
      other: "/media/downloads/other"
      radarr: "/media/downloads/movies"
      sonarr: "/media/downloads/tv"
      lidarr: "/media/downloads/music"
      readarr: "/media/downloads/books"
      radarr-imported: "/media/downloads/movies-imported"
      sonarr-imported: "/media/downloads/tv-imported"
      lidarr-imported: "/media/downloads/music-imported"
      readarr-imported: "/media/downloads/books-imported"

    tracker:
      other:
        tag: other
