apiVersion: v1
kind: ConfigMap
metadata:
  name: qbit-manage-config
  namespace: media
data:
  config.yml: |-
    commands:
      dry_run: ${qbit_manage_dry_run}
      recheck: false
      cat_update: false
      tag_update: true
      rem_unregistered: false
      tag_tracker_error: true
      rem_orphaned: false
      tag_nohardlinks: false
      share_limits: false
      skip_qb_version_check: false
      skip_cleanup: true

    qbt:
      host: "qbittorrent:8080"
      user:
      pass:

    settings:
      force_auto_tmm: false
      tracker_error_tag: issue
      nohardlinks_tag: noHL
      stalled_tag: stalledDL
      tag_stalled_torrents: true
      disable_qbt_default_share_limits: false

    directory:
      root_dir: "/downloads"
      recycle_bin: "/downloads/.RecycleBin"
      orphaned_dir: "/downloads/orphaned_data"

    cat:
      Uncategorized: "/downloads/other"
      other: "/downloads/other"
      radarr: "/downloads/radarr"
      sonarr: "/downloads/sonarr"
      lidarr: "/downloads/lidarr"
      readarr: "/downloads/readarr"
      radarr-imported: "/downloads/radarr-imported"
      sonarr-imported: "/downloads/sonarr-imported"
      lidarr-imported: "/downloads/lidarr-imported"
      readarr-imported: "/downloads/readarr-imported"

    tracker:
      other:
        tag: other
