apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: media
data:
  qBittorrent.conf: |-
    [BitTorrent]
    Session\AddTrackersFromURLEnabled=false
    Session\AdditionalTrackersURL=
    Session\GlobalMaxRatio=-1
    Session\GlobalMaxSeedingMinutes=-1
    Session\GlobalMaxInactiveSeedingMinutes=-1
    Session\Interface=tun0
    Session\InterfaceAddress=
    Session\InterfaceName=tun0
    Session\Port=6881
    Session\MaxActiveDownloads=${qbittorrent_max_active_downloads:=30}
    Session\MaxActiveTorrents=${qbittorrent_max_active_torrents:=500}
    Session\MaxActiveUploads=${qbittorrent_max_active_uploads:=300}
    Session\MaxUploads=200
    Session\QueueingSystemEnabled=true
    Session\ShareLimitAction=Stop

    [Preferences]
    WebUI\Address=*
    WebUI\CSRFProtection=false
    WebUI\HostHeaderValidation=false
    WebUI\LocalHostAuth=false
    WebUI\Port=8080
    WebUI\UseUPnP=false
    WebUI\AuthSubnetWhitelistEnabled=true
    WebUI\AuthSubnetWhitelist=${k8s_pod_cidr},${k8s_service_cidr}
    WebUI\Authentication\Enabled=false
    Downloads\SavePath=/downloads
    Downloads\TempPath=/downloads/incomplete
    Downloads\TempPathEnabled=true
