apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: media
data:
  qBittorrent.conf: |-
    [Preferences]
    WebUI\Address=*
    WebUI\CSRFProtection=false
    WebUI\HostHeaderValidation=false
    WebUI\LocalHostAuth=false
    WebUI\Port=8080
    WebUI\UseUPnP=false
    WebUI\AuthSubnetWhitelistEnabled=true
    WebUI\AuthSubnetWhitelist=${k8s_pod_cidr},${k8s_service_cidr}
    WebUI\Authentication\Enabled=false
    Downloads\SavePath=/downloads
    Downloads\TempPath=/downloads/incomplete
    Downloads\TempPathEnabled=true
