apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
  namespace: media
data:
  recyclarr.yml: |-
    # yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
    sonarr:
      sonarr:
        # Use short in-namespace service names to avoid resolver issues seen with full FQDNs
        base_url: http://sonarr:8989
        api_key: !secret sonarr_api_key
    radarr:
      radarr:
        base_url: http://radarr:7878
        api_key: !secret radarr_api_key
