apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 10m0s
  timeout: 10m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: media
      interval: 10m0s
  values:
    defaultPodOptions:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
    controllers:
      main:
        replicas: 1
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/sonarr
              tag: 4.0.16
            env:
              TZ: ${media_timezone}
              PUID: ${media_puid}
              PGID: ${media_pgid}
              ARR_APP: sonarr
              DOTNET_SYSTEM_NET_DISABLEIPV6: "1"
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 2000m
                memory: 2Gi
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: ${default_cluster_issuer}
          external-dns.alpha.kubernetes.io/target: ${cloudflare_tunnel_hostname}
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia-forwardauth-redirect@kubernetescrd
        hosts:
          - host: sonarr${public_host_suffix}.${delegating_domain}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: sonarr-tls
            hosts:
              - sonarr${public_host_suffix}.${delegating_domain}
    persistence:
      api-key-init:
        enabled: true
        type: configMap
        name: arr-api-key-init
        defaultMode: 0555
        globalMounts:
          - path: /custom-cont-init.d/10-arr-api-key.sh
            subPath: 10-arr-api-key.sh
            readOnly: true
      api-keys:
        enabled: true
        type: secret
        name: ${arr_api_keys_secret_name}
        defaultMode: 0440
        globalMounts:
          - path: /run/secrets/arr
            readOnly: true
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: ${arr_config_storage_class_name}
        size: ${arr_config_size}
        globalMounts:
          - path: /config
      downloads:
        enabled: true
        existingClaim: arr-downloads
        globalMounts:
          - path: /downloads
      media:
        enabled: true
        existingClaim: arr-media
        globalMounts:
          - path: /media
