apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  arr_config_size: "5Gi"
  arr_config_storage_class_name: "ssd-cephfs-1r"
  arr_downloads_size: "200Gi"
  arr_downloads_storage_class_name: "ssd-cephfs-1r"
  arr_media_size: "1Ti"
  arr_media_storage_class_name: "ssd-cephfs-1r"
  cloudflare_tunnel_hostname: "03ed4283-aa2e-4781-8236-fd69a38e130a.cfargotunnel.com"
  default_cluster_issuer: "letsencrypt-prod"
  delegating_domain: "h4xx.io"
  k8s_pod_cidr: "10.42.0.0/16"
  k8s_service_cidr: "10.43.0.0/16"
  media_pgid: "1000"
  media_puid: "1000"
  media_timezone: "Europe/Berlin"
  protonvpn_server_countries: "Switzerland"
