apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repo.yaml
  - helm-release.yaml
  - helm-release-cephfs.yaml
  - storageclasses.yaml
  - storageclasses-cephfs.yaml
