---
# RBD storage classes (names/pools can be overridden per cluster overlay)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "${ceph_rbd_storage_class_1r_name:=ssd-rbd-1r}"
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: "${ceph_cluster_id}"
  pool: "${ceph_rbd_storage_class_1r_pool:=k8s-ssd-1r}"
  mounter: rbd-nbd
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ${ceph_csi_namespace}
  csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ${ceph_csi_namespace}
  csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ${ceph_csi_namespace}
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "${ceph_rbd_storage_class_2r_name:=ssd-rbd-2r}"
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: "${ceph_cluster_id}"
  pool: "${ceph_rbd_storage_class_2r_pool:=k8s-ssd-2r}"
  mounter: rbd-nbd
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ${ceph_csi_namespace}
  csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ${ceph_csi_namespace}
  csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ${ceph_csi_namespace}
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "${ceph_rbd_storage_class_3r_name:=ssd-rbd-3r}"
  annotations:
    storageclass.kubernetes.io/is-default-class: "${ceph_rbd_storage_class_3r_is_default:=true}"
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: "${ceph_cluster_id}"
  pool: "${ceph_rbd_storage_class_3r_pool:=k8s-ssd-3r}"
  mounter: rbd-nbd
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ${ceph_csi_namespace}
  csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ${ceph_csi_namespace}
  csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ${ceph_csi_namespace}
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
