---
# ssd-cephfs-1r: 1 replica (no redundancy) - shared filesystem
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-cephfs-1r
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: "${ceph_cluster_id}"
  fsName: ssd-cephfs
  pool: ssd-cephfs-1r
  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ${ceph_csi_namespace}
  csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ${ceph_csi_namespace}
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ${ceph_csi_namespace}
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
# ssd-cephfs-2r: 2 replicas - shared filesystem
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-cephfs-2r
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: "${ceph_cluster_id}"
  fsName: ssd-cephfs
  pool: ssd-cephfs-2r
  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ${ceph_csi_namespace}
  csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ${ceph_csi_namespace}
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ${ceph_csi_namespace}
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
# ssd-cephfs-3r: 3 replicas - shared filesystem
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-cephfs-3r
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: "${ceph_cluster_id}"
  fsName: ssd-cephfs
  pool: ssd-cephfs-3r
  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ${ceph_csi_namespace}
  csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ${ceph_csi_namespace}
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ${ceph_csi_namespace}
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
