apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: authelia
data:
  configuration.yaml: |
    server:
      address: 'tcp://0.0.0.0:9091'

    log:
      level: info

    theme: dark
    default_redirection_url: https://nextcloud.${delegating_domain}

    authentication_backend:
      file:
        path: /config/users_database.yml

    definitions:
      user_attributes:
        nextcloud_is_admin:
          expression: '"nextcloud-admins" in groups'

    access_control:
      default_policy: deny
      rules:
        - domain: 'auth.${delegating_domain}'
          policy: bypass
        - domain: 'grafana.${delegating_domain}'
          subject:
            - 'user:testuser'
          policy: one_factor
        - domain: 'dashboard.${delegating_domain}'
          subject:
            - 'group:traefik-admins'
            - 'group:traefik-users'
          policy: two_factor
        - domain: 'grafana.${delegating_domain}'
          subject:
            - 'group:grafana-admins'
            - 'group:grafana-users'
          policy: two_factor
        - domain: 'metrics.${delegating_domain}'
          subject:
            - 'group:mimir-admins'
            - 'group:mimir-users'
          policy: two_factor
        - domain: 'logs.${delegating_domain}'
          subject:
            - 'group:loki-admins'
            - 'group:loki-users'
          policy: two_factor
        - domain: 'traces.${delegating_domain}'
          subject:
            - 'group:tempo-admins'
            - 'group:tempo-users'
          policy: two_factor
        - domain: 'nextcloud.${delegating_domain}'
          subject:
            - 'group:nextcloud-admins'
            - 'group:nextcloud-users'
          policy: two_factor
        - domain: 'collabora.${delegating_domain}'
          resources:
            - '^/cool/adminws/'
            - '^/cool/getMetrics'
            - '^/browser/dist/admin/'
          subject:
            - 'group:collabora-admins'
          policy: two_factor
        - domain: 'collabora.${delegating_domain}'
          resources:
            - '^/cool/adminws/'
            - '^/cool/getMetrics'
            - '^/browser/dist/admin/'
          policy: deny
        - domain: 'qbittorrent.${delegating_domain}'
          subject:
            - 'group:qbittorrent-admins'
            - 'group:qbittorrent-users'
          policy: two_factor
        - domain: 'prowlarr.${delegating_domain}'
          subject:
            - 'group:prowlarr-admins'
            - 'group:prowlarr-users'
          policy: two_factor
        - domain: 'sonarr.${delegating_domain}'
          subject:
            - 'group:sonarr-admins'
            - 'group:sonarr-users'
          policy: two_factor
        - domain: 'radarr.${delegating_domain}'
          subject:
            - 'group:radarr-admins'
            - 'group:radarr-users'
          policy: two_factor
        - domain: 'lidarr.${delegating_domain}'
          subject:
            - 'group:lidarr-admins'
            - 'group:lidarr-users'
          policy: two_factor
        - domain: 'readarr.${delegating_domain}'
          subject:
            - 'group:readarr-admins'
            - 'group:readarr-users'
          policy: two_factor
        - domain: 'bazarr.${delegating_domain}'
          subject:
            - 'group:bazarr-admins'
            - 'group:bazarr-users'
          policy: two_factor
        - domain: 'jellyseerr.${delegating_domain}'
          subject:
            - 'group:jellyseerr-admins'
            - 'group:jellyseerr-users'
          policy: two_factor
        - domain: 'jellyfin.${delegating_domain}'
          subject:
            - 'group:jellyfin-admins'
            - 'group:jellyfin-users'
          policy: two_factor
        - domain: '*.${delegating_domain}'
          policy: two_factor

    session:
      name: authelia_session
      same_site: lax
      expiration: 1h
      inactivity: 15m
      domain: ${delegating_domain}

    storage:
      local:
        path: /config/db.sqlite3

    identity_providers:
      oidc:
        claims_policies:
          nextcloud:
            custom_claims:
              nextcloud_is_admin:
                name: is_admin
                attribute: nextcloud_is_admin
          grafana:
            id_token:
              - email
              - name
              - groups
              - preferred_username
        scopes:
          nextcloud_admin:
            claims:
              - is_admin
        jwks:
          - key: {{ secret "/secrets/authelia-oidc/identity_providers.oidc.jwks.rsa.2048.key" | mindent 14 "|" | msquote }}
            algorithm: 'RS256'
            use: 'sig'
        clients:
          - client_id: nextcloud
            client_name: Nextcloud
            client_secret: {{ secret "/secrets/authelia-oidc/identity_providers.oidc.client.nextcloud.secret" | msquote }}
            authorization_policy: two_factor
            consent_mode: implicit
            claims_policy: nextcloud
            redirect_uris:
              - https://nextcloud.${delegating_domain}/apps/oidc_login/oidc
              - https://nextcloud.${delegating_domain}/index.php/apps/oidc_login/oidc
            scopes:
              - openid
              - profile
              - email
              - groups
              - offline_access
              - nextcloud_admin
            grant_types:
              - authorization_code
              - refresh_token
            response_types:
              - code
          - client_id: grafana
            client_name: Grafana
            client_secret: {{ secret "/secrets/authelia-oidc/identity_providers.oidc.client.grafana.secret" | msquote }}
            authorization_policy: one_factor
            consent_mode: implicit
            claims_policy: grafana
            redirect_uris:
              - https://grafana.${delegating_domain}/login/generic_oauth
              - https://grafana.${delegating_domain}/login/generic_oauth/
            scopes:
              - openid
              - profile
              - email
              - groups
            grant_types:
              - authorization_code
              - refresh_token
            response_types:
              - code
          - client_id: jellyfin
            client_name: Jellyfin
            client_secret: {{ secret "/secrets/authelia-oidc/identity_providers.oidc.client.jellyfin.secret" | msquote }}
            public: false
            authorization_policy: two_factor
            require_pkce: true
            pkce_challenge_method: 'S256'
            redirect_uris:
              - https://jellyfin.${delegating_domain}/sso/OID/redirect/authelia
            scopes:
              - openid
              - profile
              - email
              - groups
            response_types:
              - code
            grant_types:
              - authorization_code
            access_token_signed_response_alg: none
            userinfo_signed_response_alg: none
            token_endpoint_auth_method: client_secret_post

    notifier:
      smtp:
        address: '${authelia_smtp_address}'
        startup_check_address: '${authelia_smtp_startup_check_address}'
