apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 10m0s
  timeout: 10m0s
  chart:
    spec:
      chart: authelia
      version: 0.10.49
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: authelia
      interval: 10m0s
  install:
    disableOpenAPIValidation: true
    disableSchemaValidation: true
  upgrade:
    disableOpenAPIValidation: true
    disableSchemaValidation: true
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: 03ed4283-aa2e-4781-8236-fd69a38e130a.cfargotunnel.com
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - auth.h4xx.io
      tls:
        enabled: true
        secret: authelia-tls
    configMap:
      disabled: false
      existingConfigMap: authelia-config
      session:
        cookies:
          - domain: h4xx.io
            same_site: lax
    pod:
      extraVolumeMounts:
        - name: authelia-users
          mountPath: /config/users_database.yml
          subPath: users_database.yml
      extraVolumes:
        - name: authelia-users
          secret:
            secretName: authelia-users
    persistence:
      enabled: true
      storageClass: ssd-rbd-2r
      size: 1Gi
