apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 10m0s
  timeout: 10m0s
  chart:
    spec:
      chart: authelia
      version: 0.10.49
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: authelia
      interval: 10m0s
  install:
    disableOpenAPIValidation: true
    disableSchemaValidation: true
  upgrade:
    disableOpenAPIValidation: true
    disableSchemaValidation: true
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: ${default_cluster_issuer}
        external-dns.alpha.kubernetes.io/target: ${cloudflare_tunnel_hostname}
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      rulesOverride:
        - host: auth.${delegating_domain}
          path: /
      tls:
        enabled: true
        secret: authelia-tls
    configMap:
      disabled: false
      existingConfigMap: authelia-config
      session:
        cookies:
          - domain: ${delegating_domain}
            same_site: lax
      notifier:
        smtp:
          enabled: true
          password:
            secret_name: authelia-mail-credentials
            path: password
      identity_providers:
        oidc:
          enabled: true
          hmac_secret:
            secret_name: authelia-oidc
            path: identity_providers.oidc.hmac.key
      telemetry:
        metrics:
          enabled: true
          port: 9959
    secret:
      existingSecret: authelia-secrets
      additionalSecrets:
        authelia-mail-credentials: {}
        authelia-oidc: {}
    pod:
      annotations:
        reloader.stakater.com/auto: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9959"
        prometheus.io/path: "/metrics"
      env:
        - name: AUTHELIA_NOTIFIER_SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: authelia-mail-credentials
              key: username
        - name: AUTHELIA_NOTIFIER_SMTP_SENDER
          valueFrom:
            secretKeyRef:
              name: authelia-mail-credentials
              key: sender
      extraVolumeMounts:
        - name: authelia-users
          mountPath: /config/users_database.yml
          subPath: users_database.yml
      extraVolumes:
        - name: authelia-users
          secret:
            secretName: authelia-users
    persistence:
      enabled: true
      storageClass: ${default_sts_storage_class_name}
      size: 1Gi
