apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - postgres.yaml
  - backup-bucket-bootstrap.yaml
  - scheduled-backup.yaml
  - valkey-helm-repo.yaml
  - valkey-helm-release.yaml
  - helm-repo.yaml
  - helm-release.yaml
