apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-postgres
  namespace: authelia
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
      prometheus.io/path: "/metrics"
  bootstrap:
    initdb:
      database: authelia
      owner: authelia
  backup:
    barmanObjectStore:
      destinationPath: "s3://${authelia_postgres_backup_bucket:=authelia-postgres-backup}/${cluster_environment}/${authelia_postgres_backup_generation:=}authelia-postgres/"
      endpointURL: "${authelia_postgres_backup_endpoint_url:=}"
      serverName: ${authelia_postgres_backup_server_name:=authelia-postgres}
      s3Credentials:
        accessKeyId:
          name: ${authelia_postgres_backup_credential_secret_name:=authelia-postgres-backup-credentials}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: ${authelia_postgres_backup_credential_secret_name:=authelia-postgres-backup-credentials}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "${authelia_postgres_backup_retention:=30d}"
  storage:
    storageClass: ${authelia_postgres_storage_class_name:=${default_sts_storage_class_name}}
    size: ${authelia_postgres_size:=2Gi}
  resources:
    requests:
      cpu: ${authelia_postgres_requests_cpu:=50m}
      memory: ${authelia_postgres_requests_memory:=128Mi}
    limits:
      cpu: ${authelia_postgres_limits_cpu:=500m}
      memory: ${authelia_postgres_limits_memory:=512Mi}
