apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  stalwart_suspend: "true"
  stalwart_blob_bucket: "stalwart-blobs"
  stalwart_blob_region: "homelab"
  stalwart_image_tag: "v0.16.25"
  stalwart_limits_memory: "2Gi"
  stalwart_log_level: "info"
  stalwart_mail_hostname: "mail.hackimpott.de"
  stalwart_postgres_backup_bucket: "stalwart-postgres-backup"
  stalwart_postgres_backup_credential_secret_name: "stalwart-postgres-backup-credentials"
  stalwart_postgres_backup_cron: "0 15 4 * * *"
  stalwart_postgres_backup_endpoint_url: ""
  stalwart_postgres_backup_generation: ""
  stalwart_postgres_backup_retention: "30d"
  stalwart_postgres_backup_server_name: "stalwart-postgres"
  stalwart_postgres_instances: "3"
  stalwart_postgres_limits_memory: "2Gi"
  stalwart_postgres_requests_cpu: "100m"
  stalwart_postgres_requests_memory: "512Mi"
  stalwart_postgres_size: "20Gi"
  stalwart_postgres_storage_class_name: "longhorn-nvme-rwo-2r"
  stalwart_replicas: ""
  stalwart_requests_cpu: "200m"
  stalwart_requests_memory: "512Mi"
  stalwart_valkey_image_tag: "9.1.2-alpine"
