apiVersion: v1
kind: Service
metadata:
  name: ${s3_service_name}
  namespace: ${s3_namespace}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
    prometheus.io/path: "/minio/v2/metrics/cluster"
spec:
  selector:
    app.kubernetes.io/name: s3
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
