apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${s3_service_name}
  namespace: ${s3_namespace}
spec:
  serviceName: ${s3_service_name}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: s3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: s3
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args:
            - server
            - /data
            - --console-address=:9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: ${s3_root_secret_name}
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${s3_root_secret_name}
                  key: rootPassword
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: api
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: api
            periodSeconds: 20
          resources:
            requests:
              cpu: ${s3_requests_cpu}
              memory: ${s3_requests_memory}
            limits:
              cpu: ${s3_limits_cpu}
              memory: ${s3_limits_memory}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ${s3_storage_class_name}
        resources:
          requests:
            storage: ${s3_data_size}
