apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  matrix_mas_suspend: "true"
  matrix_mas_preflight_suspend: "true"
  matrix_mas_cutover_suspend: "true"
  matrix_mas_image: "ghcr.io/element-hq/matrix-authentication-service:1.21.0@sha256:9b5013992767f9e67ca10848e1f4c7951e335360cd70f8f5427adc21bb185d8c"
  matrix_mas_replicas: "0"
  matrix_mas_synapse_kind: "synapse_read_only"
  matrix_mas_upstream_provider_id: "01K1ZQ2A9S7F4P8K6W3C5D0R1T"
  matrix_mas_preflight_generation: "disabled"
  matrix_mas_cutover_generation: "disabled"
  matrix_mas_requests_cpu: "50m"
  matrix_mas_requests_memory: "64Mi"
  matrix_mas_limits_cpu: "500m"
  matrix_mas_limits_memory: "384Mi"
  matrix_mas_postgres_user: "mas"
  matrix_mas_postgres_database: "mas"
  matrix_mas_postgres_instances: "1"
  matrix_mas_postgres_storage_class_name: "longhorn-rwo-1r"
  matrix_mas_postgres_size: "10Gi"
  matrix_mas_postgres_requests_cpu: "100m"
  matrix_mas_postgres_requests_memory: "256Mi"
  matrix_mas_postgres_limits_cpu: "1000m"
  matrix_mas_postgres_limits_memory: "1Gi"
  matrix_mas_postgres_backup_retention: "30d"
  matrix_masdb_backup_generation: ""
  matrix_masdb_backup_server_name: "matrix-mas-postgres"
