apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: ${longhorn_namespace}
spec:
  interval: 10m0s
  timeout: 15m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: longhorn
      version: '>=1.7.0 <2.0.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: ${longhorn_namespace}
      interval: 10m0s
  values:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9500"
      prometheus.io/path: "/metrics"
    defaultSettings:
      defaultReplicaCount: ${longhorn_default_replica_count}
      replicaSoftAntiAffinity: ${longhorn_replica_soft_anti_affinity:=false}
      allowRecurringJobWhileVolumeDetached: ${longhorn_allow_recurring_job_while_volume_detached:=true}
      storageMinimalAvailablePercentage: ${longhorn_storage_minimal_available_percentage:=10}
      storageOverProvisioningPercentage: ${longhorn_storage_over_provisioning_percentage:=100}
      storageReservedPercentageForDefaultDisk: ${longhorn_storage_reserved_percentage_for_default_disk:=10}
    defaultBackupStore:
      backupTarget: ${longhorn_backup_target:=}
      backupTargetCredentialSecret: ${longhorn_backup_target_credential_secret_name:=}
      pollInterval: ${longhorn_backup_poll_interval:=300}
    longhornManager:
      serviceAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9500"
        prometheus.io/path: "/metrics"
      resources:
        requests:
          cpu: ${longhorn_manager_requests_cpu:=100m}
          memory: ${longhorn_manager_requests_memory:=512Mi}
        limits:
          cpu: ${longhorn_manager_limits_cpu:=1000m}
          memory: ${longhorn_manager_limits_memory:=2Gi}
    persistence:
      defaultClass: false
      defaultClassReplicaCount: ${longhorn_default_replica_count}
      reclaimPolicy: "${longhorn_storage_class_reclaim_policy:=Retain}"
    ingress:
      enabled: false
