apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-exporter
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud-exporter
    app.kubernetes.io/part-of: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud-exporter
        app.kubernetes.io/part-of: nextcloud
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9205"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: exporter
          image: ghcr.io/xperimental/nextcloud-exporter:v0.9.0
          ports:
            - name: metrics
              containerPort: 9205
              protocol: TCP
          env:
            - name: NEXTCLOUD_SERVER
              value: https://nextcloud.${delegating_domain}
            - name: NEXTCLOUD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin
                  key: username
            - name: NEXTCLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin
                  key: password
            - name: NEXTCLOUD_TLS_SKIP_VERIFY
              value: "false"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-exporter
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud-exporter
    app.kubernetes.io/part-of: nextcloud
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9205
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: nextcloud-exporter
