apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgres
  namespace: nextcloud
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: ${default_sts_storage_class_name}
    size: 10Gi
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
