apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgres
  namespace: nextcloud
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
      prometheus.io/path: "/metrics"
  storage:
    storageClass: ${nextcloud_postgres_storage_class_name:=${default_sts_storage_class_name}}
    size: ${nextcloud_postgres_size}
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
  backup:
    barmanObjectStore:
      destinationPath: "s3://${nextcloud_postgres_backup_bucket}/${cluster_environment}/${nextcloud_postgres_backup_generation:=}nextcloud-postgres/"
      endpointURL: "${nextcloud_postgres_backup_endpoint_url:=}"
      serverName: ${nextcloud_postgres_backup_server_name:=nextcloud-postgres}
      s3Credentials:
        accessKeyId:
          name: ${nextcloud_postgres_backup_credential_secret_name}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: ${nextcloud_postgres_backup_credential_secret_name}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
