apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-photos-shared
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${nextcloud_photos_size:=50Gi}
  storageClassName: ${longhorn_rwx_storage_class_1r_name}
