apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${nextcloud_photos_claim_name:=nextcloud-photos-shared}
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${nextcloud_photos_size:=50Gi}
  storageClassName: ${nextcloud_photos_storage_class_name:=${longhorn_rwx_storage_class_1r_name}}
