apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-app
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${nextcloud_app_size}
  storageClassName: ${nextcloud_app_storage_class_name}
