apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${nextcloud_data_claim_name}
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${nextcloud_data_size}
  storageClassName: ${nextcloud_data_storage_class_name}
