apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-postgres
  namespace: nextcloud
spec:
  schedule: "${nextcloud_postgres_backup_cron:=0 0 3 * * *}"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: nextcloud-postgres
