apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-postgres
  namespace: nextcloud
spec:
  # Suspended 2026-09-22 with the cluster's barmanObjectStore (storage01 full).
  suspend: true
  schedule: "${nextcloud_postgres_backup_cron:=0 0 3 * * *}"
  backupOwnerReference: self
  immediate: false
  cluster:
    name: nextcloud-postgres
