apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailpit-data
  namespace: mailpit
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${mailpit_storage_class_name:=longhorn-ssd-rwo-1r}
  resources:
    requests:
      storage: ${mailpit_data_size:=2Gi}
