apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  forgejo_suspend: "true"
  forgejo_namespace: "forgejo"
  forgejo_service_name: "forgejo"
  forgejo_image: "codeberg.org/forgejo/forgejo:15.0.3-rootless"
  forgejo_image_pull_policy: "IfNotPresent"
  forgejo_replicas: "1"
  forgejo_admin_secret_name: "forgejo-admin"
  forgejo_data_storage_class_name: "longhorn-ssd-rwo-1r"
  forgejo_data_size: "50Gi"
  forgejo_ssh_public_port: "!!str 2222"
  forgejo_requests_cpu: "250m"
  forgejo_requests_memory: "512Mi"
  forgejo_requests_ephemeral_storage: "256Mi"
  forgejo_limits_memory: "2Gi"
  forgejo_limits_ephemeral_storage: "2Gi"
  forgejo_postgres_cluster_name: "forgejo-postgres"
  forgejo_postgres_image: "ghcr.io/cloudnative-pg/postgresql:18-system-trixie"
  forgejo_postgres_instances: "1"
  forgejo_postgres_db_name: "forgejo"
  forgejo_postgres_user: "forgejo"
  forgejo_postgres_storage_class_name: "longhorn-nvme-rwo-1r"
  forgejo_postgres_size: "20Gi"
  forgejo_postgres_requests_cpu: "100m"
  forgejo_postgres_requests_memory: "256Mi"
  forgejo_postgres_limits_memory: "1Gi"
  forgejo_postgres_backup_bucket: "forgejo-postgres-backup"
  forgejo_postgres_backup_endpoint_url: ""
  forgejo_postgres_backup_generation: ""
  forgejo_postgres_backup_server_name: "forgejo-postgres"
  forgejo_postgres_backup_credential_secret_name: "forgejo-postgres-backup-credentials"
  forgejo_postgres_backup_retention: "30d"
  forgejo_postgres_backup_cron: "0 0 2 * * *"
