apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m0s
  timeout: 10m0s
  chart:
    spec:
      chart: external-dns
      version: 1.14.5
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 10m0s
  values:
    provider: cloudflare
    domainFilters:
      - ${delegating_domain}
    sources:
      - ingress
      - service
    policy: upsert-only
    txtOwnerId: ${external_dns_txt_owner_id}
    extraArgs:
      - --cloudflare-proxied
      - --metrics-address=0.0.0.0:7979
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "7979"
      prometheus.io/path: "/metrics"
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 192Mi
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token
