apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  longhorn_namespace: "longhorn-system"
  longhorn_default_replica_count: "3"
  longhorn_rwo_storage_class_1r_name: "longhorn-rwo-1r"
  longhorn_rwo_storage_class_1r_replicas: "1"
  longhorn_rwo_storage_class_2r_name: "longhorn-rwo-2r"
  longhorn_rwo_storage_class_2r_replicas: "2"
  longhorn_rwo_storage_class_3r_name: "longhorn-rwo-3r"
  longhorn_rwo_storage_class_3r_replicas: "3"
  longhorn_rwo_storage_class_3r_is_default: "false"
  longhorn_rwx_storage_class_1r_name: "longhorn-rwx-1r"
  longhorn_rwx_storage_class_1r_replicas: "1"
  longhorn_rwx_storage_class_2r_name: "longhorn-rwx-2r"
  longhorn_rwx_storage_class_2r_replicas: "2"
  longhorn_rwx_storage_class_3r_name: "longhorn-rwx-3r"
  longhorn_rwx_storage_class_3r_replicas: "3"
  longhorn_nvme_disk_selector: "nvme"
  longhorn_ssd_disk_selector: "ssd"
  longhorn_nvme_rwo_storage_class_1r_name: "longhorn-nvme-rwo-1r"
  longhorn_nvme_rwo_storage_class_1r_replicas: "1"
  longhorn_nvme_rwo_storage_class_2r_name: "longhorn-nvme-rwo-2r"
  longhorn_nvme_rwo_storage_class_2r_replicas: "2"
  longhorn_nvme_rwo_storage_class_3r_name: "longhorn-nvme-rwo-3r"
  longhorn_nvme_rwo_storage_class_3r_replicas: "3"
  longhorn_nvme_rwx_storage_class_1r_name: "longhorn-nvme-rwx-1r"
  longhorn_nvme_rwx_storage_class_1r_replicas: "1"
  longhorn_nvme_rwx_storage_class_2r_name: "longhorn-nvme-rwx-2r"
  longhorn_nvme_rwx_storage_class_2r_replicas: "2"
  longhorn_nvme_rwx_storage_class_3r_name: "longhorn-nvme-rwx-3r"
  longhorn_nvme_rwx_storage_class_3r_replicas: "3"
  longhorn_ssd_rwo_storage_class_1r_name: "longhorn-ssd-rwo-1r"
  longhorn_ssd_rwo_storage_class_1r_replicas: "1"
  longhorn_ssd_rwo_storage_class_2r_name: "longhorn-ssd-rwo-2r"
  longhorn_ssd_rwo_storage_class_2r_replicas: "2"
  longhorn_ssd_rwo_storage_class_3r_name: "longhorn-ssd-rwo-3r"
  longhorn_ssd_rwo_storage_class_3r_replicas: "3"
  longhorn_ssd_rwx_storage_class_1r_name: "longhorn-ssd-rwx-1r"
  longhorn_ssd_rwx_storage_class_1r_replicas: "1"
  longhorn_ssd_rwx_storage_class_2r_name: "longhorn-ssd-rwx-2r"
  longhorn_ssd_rwx_storage_class_2r_replicas: "2"
  longhorn_ssd_rwx_storage_class_3r_name: "longhorn-ssd-rwx-3r"
  longhorn_ssd_rwx_storage_class_3r_replicas: "3"
  longhorn_allow_recurring_job_while_volume_detached: "true"
  longhorn_backup_target: ""
  longhorn_backup_target_credential_secret_name: ""
  longhorn_backup_poll_interval: "300"
  longhorn_backup_bootstrap_cron: "0,30 * * * *"
  longhorn_recurring_backup_cron: "15 3 * * *"
  longhorn_recurring_backup_retain: "14"
  longhorn_recurring_full_backup_interval: "7"
