apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  cloudflare_tunnel_hostname: "03ed4283-aa2e-4781-8236-fd69a38e130a.cfargotunnel.com"
  default_cluster_issuer: "letsencrypt-prod"
  default_sts_storage_class_name: "ssd-rbd-2r"
  delegating_domain: "h4xx.io"
  nextcloud_app_size: "20Gi"
  nextcloud_app_claim_name: "nextcloud-app"
  nextcloud_app_storage_class_name: "ssd-cephfs-2r"
  nextcloud_data_size: "500Gi"
  nextcloud_data_claim_name: "nextcloud-nextcloud-data"
  nextcloud_data_storage_class_name: "ssd-cephfs-2r"
  nextcloud_hpa_enabled: "false"
  nextcloud_hpa_cpu_threshold: "60"
  nextcloud_hpa_max_pods: "3"
  nextcloud_hpa_min_pods: "1"
  nextcloud_resources_limits_memory: "2Gi"
  nextcloud_resources_requests_cpu: "200m"
  nextcloud_resources_requests_memory: "512Mi"
  trusted_proxies_cidr: "10.42.0.0/16"
  valkey_auth_secret_name: "nextcloud-valkey"
