apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  authelia_smtp_address: "submission://posteo.de:587"
  authelia_smtp_startup_check_address: "h4xx@posteo.de"
  authelia_access_policy: "two_factor"
  authelia_oidc_policy: "two_factor"
  immich_oidc_client_id: "immich"
  immich_photos_oidc_client_id: "immich-photos"
  cloudflare_tunnel_hostname: "03ed4283-aa2e-4781-8236-fd69a38e130a.cfargotunnel.com"
  default_cluster_issuer: "letsencrypt-prod"
  default_sts_storage_class_name: "ssd-rbd-2r"
  delegating_domain: "h4xx.io"
