apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  hydra_suspend: "true"
  hydra_namespace: nix-cache
  hydra_service_name: hydra
  hydra_service_port: "3000"
  hydra_nix_image_tag: "2.32.8"
  hydra_nix_packages: github:NixOS/nixpkgs/nixos-26.05#hydra github:NixOS/nixpkgs/nixos-26.05#curl github:NixOS/nixpkgs/nixos-26.05#git github:NixOS/nixpkgs/nixos-26.05#jq github:NixOS/nixpkgs/nixos-26.05#openssh
  hydra_nix_extra_packages: github:NixOS/nixpkgs/nixos-26.05#shadow
  hydra_public_url: https://hydra.example.com
  hydra_admin_secret_name: hydra-admin
  hydra_jobset_flake: git+https://github.com/lukasfriedhoff/nix.git?ref=develop
  hydra_jobset_check_interval: "3600"
  hydra_jobset_keep_nr: "3"
  hydra_binary_cache_public_uri: https://attic.example.com/homelab
  hydra_notification_sender: hydra@example.com
  hydra_storage_class_name: longhorn-disk-rwo-1r
  hydra_storage_size: 100Gi
  hydra_requests_cpu: 500m
  hydra_requests_memory: 2Gi
  hydra_requests_ephemeral_storage: 4Gi
  hydra_limits_cpu: "4"
  hydra_limits_memory: 8Gi
  hydra_limits_ephemeral_storage: 32Gi
  hydra_nix_max_jobs: "2"
  hydra_nix_cores: "4"
  hydra_max_servers: "8"
  hydra_min_spare_servers: "1"
  hydra_max_spare_servers: "2"
  hydra_evaluator_max_memory_size: "4096"
  hydra_max_output_size: "4294967296"
  hydra_nix_substituters: https://cache.nixos.org/ https://attic.example.com/homelab
  hydra_nix_trusted_public_keys: homelab:REPLACE_ME cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
  hydra_postgres_cluster_name: hydra-postgres
  hydra_postgres_image: ghcr.io/cloudnative-pg/postgresql:18-system-trixie
  hydra_postgres_instances: "1"
  hydra_postgres_db_name: hydra
  hydra_postgres_user: hydra
  hydra_postgres_storage_class_name: longhorn-disk-rwo-1r
  hydra_postgres_size: 20Gi
  hydra_postgres_requests_cpu: 250m
  hydra_postgres_requests_memory: 512Mi
  hydra_postgres_requests_ephemeral_storage: 1Gi
  hydra_postgres_limits_cpu: "2"
  hydra_postgres_limits_memory: 2Gi
  hydra_postgres_limits_ephemeral_storage: 4Gi
