apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  logday_suspend: "true"
  logday_image_repository: "ghcr.io/lukasfriedhoff/logday"
  logday_image_tag: "latest"
  logday_traefik_middlewares: "logday-logday-nuxt-rewrite@kubernetescrd,traefik-authelia-forwardauth-redirect@kubernetescrd"
  logday_replicas: "1"
  logday_requests_cpu: "100m"
  logday_requests_memory: "256Mi"
  logday_limits_cpu: "1000m"
  logday_limits_memory: "1Gi"
  logday_db_sslmode: "require"
  logday_db_auto_migrate: "true"
  logday_db_connect_retries: "15"
  logday_postgres_cluster_name: "logday-postgres"
  logday_postgres_db_name: "logday_db"
  logday_postgres_user: "logday_user"
  logday_postgres_instances: "1"
  logday_postgres_image: "ghcr.io/cloudnative-pg/postgresql:17.6-system-trixie"
  logday_postgres_storage_class_name: "longhorn-rwo-1r"
  logday_postgres_size: "10Gi"
  logday_postgres_backup_enabled: "true"
  logday_postgres_backup_bucket: "logday-postgres-backup"
  logday_postgres_backup_cron: "0 0 2 * * *"
  logday_postgres_backup_endpoint_url: ""
  logday_postgres_backup_generation: ""
  logday_postgres_backup_server_name: "logday-postgres"
  logday_postgres_backup_credential_secret_name: "logday-postgres-backup-credentials"
  logday_postgres_backup_retention: "30d"
  logday_postgres_requests_cpu: "100m"
  logday_postgres_requests_memory: "256Mi"
  logday_postgres_limits_cpu: "1000m"
  logday_postgres_limits_memory: "1Gi"
