apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  moonlight_suspend: "true"
  moonlight_image_tag: "latest"
  moonlight_requests_cpu: "100m"
  moonlight_requests_memory: "256Mi"
  moonlight_limits_cpu: "2000m"
  moonlight_limits_memory: "1Gi"
  moonlight_config_storage_class_name: "longhorn-rwo-1r"
  moonlight_config_size: "10Gi"
  moonlight_webrtc_port_range: "40000:40100"

