apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  cloudflare_tunnel_hostname: "03ed4283-aa2e-4781-8236-fd69a38e130a.cfargotunnel.com"
  default_cluster_issuer: "letsencrypt-prod"
  default_sts_storage_class_name: "ssd-rbd-1r"
  delegating_domain: "h4xx.io"
  navigation_namespace: "navigation"
  public_host_suffix: ""
  valhalla_adapter_ingress_middlewares: "traefik-authelia-forwardauth-redirect@kubernetescrd"
  valhalla_adapter_limits_cpu: "500m"
  valhalla_adapter_limits_memory: "512Mi"
  valhalla_adapter_rate_limit_max: "!!str 120"
  valhalla_adapter_rate_limit_window_ms: "!!str 60000"
  valhalla_adapter_require_token: "!!str false"
  valhalla_adapter_requests_cpu: "50m"
  valhalla_adapter_requests_memory: "128Mi"
  valhalla_adapter_token_secret_name: "valhalla-osmand-token"
  valhalla_build_admins: "!!str True"
  valhalla_build_elevation: "!!str False"
  valhalla_build_tar: "!!str True"
  valhalla_build_time_zones: "!!str True"
  valhalla_data_size: "20Gi"
  valhalla_force_rebuild: "!!str False"
  valhalla_image_tag: "3.7.0"
  valhalla_ingress_middlewares: "traefik-authelia-forwardauth-redirect@kubernetescrd"
  valhalla_limits_cpu: "4000m"
  valhalla_limits_memory: "8Gi"
  valhalla_osmand_adapter_node_tag: "22-alpine"
  valhalla_requests_cpu: "500m"
  valhalla_requests_memory: "1Gi"
  valhalla_reset_marker: "none"
  valhalla_server_threads: "!!str 2"
  valhalla_startup_failure_threshold: "120"
  valhalla_startup_period_seconds: "10"
  valhalla_storage_class_name: "ssd-rbd-1r"
  valhalla_tile_urls: "https://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf"
  valhalla_traffic_name: "''"
  valhalla_use_tiles_ignore_pbf: "!!str True"
