apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  cloudflare_tunnel_hostname: "03ed4283-aa2e-4781-8236-fd69a38e130a.cfargotunnel.com"
  default_cluster_issuer: "letsencrypt-prod"
  delegating_domain: "h4xx.io"
  grafana_persistence_size: "5Gi"
  k8s_monitoring_chart_version: "3.4.0"
  k8s_monitoring_namespace: "monitoring"
  loki_backend_replicas: "1"
  loki_read_replicas: "1"
  loki_replication_factor: "1"
  loki_write_replicas: "1"
  mimir_ingester_replicas: "3"
  mimir_ingester_zone_aware_replication: "true"
  mimir_querier_replicas: "2"
  mimir_query_scheduler_replicas: "2"
  mimir_store_gateway_replicas: "1"
  mimir_store_gateway_zone_aware_replication: "true"
  monitoring_loki_bucket: "homelab-loki"
  monitoring_mimir_alertmanager_bucket: "homelab-mimir-alertmanager"
  monitoring_mimir_blocks_bucket: "homelab-mimir-blocks"
  monitoring_mimir_ruler_bucket: "homelab-mimir-ruler"
  monitoring_s3_endpoint: "srv1.lab.h4xx.io:7480"
  monitoring_s3_force_path_style: "true"
  monitoring_s3_insecure: "true"
  monitoring_s3_region: "us-east-1"
  monitoring_storage_class_name: "ssd-rbd-2r"
  monitoring_tempo_bucket: "homelab-tempo"
  monitoring_tenant_id: "anonymous"
  tempo_ingester_replicas: "3"
