apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${forgejo_postgres_cluster_name}
  namespace: ${forgejo_namespace}
  labels:
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/component: database
spec:
  imageName: ${forgejo_postgres_image}
  instances: ${forgejo_postgres_instances}
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: ${forgejo_postgres_db_name}
      owner: ${forgejo_postgres_user}
  backup:
    barmanObjectStore:
      destinationPath: "s3://${forgejo_postgres_backup_bucket:=forgejo-postgres-backup}/${cluster_environment}/${forgejo_postgres_backup_generation:=}forgejo-postgres/"
      endpointURL: "${forgejo_postgres_backup_endpoint_url:=}"
      serverName: ${forgejo_postgres_backup_server_name:=forgejo-postgres}
      s3Credentials:
        accessKeyId:
          name: ${forgejo_postgres_backup_credential_secret_name:=forgejo-postgres-backup-credentials}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: ${forgejo_postgres_backup_credential_secret_name:=forgejo-postgres-backup-credentials}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "${forgejo_postgres_backup_retention:=30d}"
  storage:
    storageClass: ${forgejo_postgres_storage_class_name}
    size: ${forgejo_postgres_size}
  resources:
    requests:
      cpu: ${forgejo_postgres_requests_cpu}
      memory: ${forgejo_postgres_requests_memory}
    limits:
      memory: ${forgejo_postgres_limits_memory}
