apiVersion: v1
kind: Service
metadata:
  name: ${forgejo_service_name}
  namespace: ${forgejo_namespace}
  labels:
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
    - name: ssh
      port: 2222
      targetPort: ssh
      protocol: TCP
