apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../matrix
patches:
  - target:
      version: v1
      kind: Service
      name: synapsedb-source
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: synapsedb-source
        namespace: matrix
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: synapsedb
    patch: |-
      - op: remove
        path: /spec/bootstrap/initdb/import
      - op: remove
        path: /spec/externalClusters
  - target:
      version: v1
      kind: Service
      name: whatsappdb-source
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: whatsappdb-source
        namespace: matrix
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: whatsappdb
    patch: |-
      - op: remove
        path: /spec/bootstrap/initdb/import
      - op: remove
        path: /spec/externalClusters
  - target:
      version: v1
      kind: Service
      name: wadb-source
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: wadb-source
        namespace: matrix
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: wadb
    patch: |-
      - op: remove
        path: /spec/bootstrap/initdb/import
      - op: remove
        path: /spec/externalClusters
  - target:
      version: v1
      kind: Service
      name: telegramdb-source
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: telegramdb-source
        namespace: matrix
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: telegramdb
    patch: |-
      - op: remove
        path: /spec/bootstrap/initdb/import
      - op: remove
        path: /spec/externalClusters
  - target:
      version: v1
      kind: Service
      name: signaldbprivate-source
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: signaldbprivate-source
        namespace: matrix
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: signaldbprivate
    patch: |-
      - op: remove
        path: /spec/bootstrap/initdb/import
      - op: remove
        path: /spec/externalClusters
