apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pretix-postgres
  namespace: pretix
spec:
  instances: ${pretix_postgres_instances:=1}
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
      prometheus.io/path: "/metrics"
  bootstrap:
    initdb:
      database: pretix
      owner: pretix
  backup:
    barmanObjectStore:
      destinationPath: "s3://${pretix_postgres_backup_bucket:=pretix-postgres-backup}/${cluster_environment}/${pretix_postgres_backup_generation:=}pretix-postgres/"
      endpointURL: "${pretix_postgres_backup_endpoint_url:=}"
      serverName: ${pretix_postgres_backup_server_name:=pretix-postgres}
      s3Credentials:
        accessKeyId:
          name: ${pretix_postgres_backup_credential_secret_name:=pretix-postgres-backup-credentials}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: ${pretix_postgres_backup_credential_secret_name:=pretix-postgres-backup-credentials}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "${pretix_postgres_backup_retention:=30d}"
  storage:
    storageClass: ${pretix_postgres_storage_class_name:=longhorn-nvme-rwo-2r}
    size: ${pretix_postgres_size:=8Gi}
  resources:
    requests:
      cpu: ${pretix_postgres_requests_cpu:=50m}
      memory: ${pretix_postgres_requests_memory:=256Mi}
    limits:
      memory: ${pretix_postgres_limits_memory:=1Gi}
