apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pretix-data
  namespace: pretix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${pretix_data_storage_class_name:=longhorn-ssd-rwo-1r}
  resources:
    requests:
      storage: ${pretix_data_size:=5Gi}
