apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${immich_photos_shared_pv_name:=immich-photos-shared-pv}
spec:
  capacity:
    storage: ${nextcloud_photos_size:=50Gi}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: ${photos_shared_nfs_server}
    path: ${photos_shared_nfs_path:=/export}
  claimRef:
    namespace: immich-photos
    name: ${immich_photos_shared_claim_name:=immich-photos-shared}
