apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-photos-shared-pv
spec:
  capacity:
    storage: ${nextcloud_photos_size:=50Gi}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: ${photos_shared_nfs_server}
    path: /
  claimRef:
    namespace: immich-photos
    name: immich-photos-shared
