apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${immich_photos_shared_claim_name:=immich-photos-shared}
  namespace: immich-photos
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${immich_photos_shared_storage_class_name:=${default_storage_class_name}}
  resources:
    requests:
      storage: ${nextcloud_photos_size:=50Gi}
