apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos-shared
  namespace: immich-photos
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-photos-shared-pv
  resources:
    requests:
      storage: ${nextcloud_photos_size}
