apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  nix_remote_builder_suspend: "true"
  nix_remote_builder_namespace: nix-cache
  nix_remote_builder_service_name: nix-remote-builder
  nix_remote_builder_image_tag: "2.32.8"
  nix_remote_builder_ssh_port: "22"
  nix_remote_builder_hostkey_secret_name: nix-remote-builder-hostkey
  nix_remote_builder_storage_class_name: longhorn-disk-rwo-1r
  nix_remote_builder_storage_size: 100Gi
  nix_remote_builder_requests_cpu: 500m
  nix_remote_builder_requests_memory: 512Mi
  nix_remote_builder_limits_cpu: 4000m
  nix_remote_builder_limits_memory: 4Gi
  nix_remote_builder_authorized_key: ssh-ed25519 AAAA... replace-me
