apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  attic_suspend: "true"
  attic_namespace: "nix-cache"
  attic_service_name: "attic"
  attic_service_port: "8080"
  attic_image: "ghcr.io/zhaofengli/attic:latest"
  attic_image_pull_policy: "IfNotPresent"
  attic_replicas: "1"
  attic_public_url: "https://attic.example.com"
  attic_api_endpoint: "https://attic.example.com"
  attic_server_secret_name: "attic-server-env"
  attic_cache_name: "homelab"
  attic_cache_priority: "30"
  attic_storage_class_name: "longhorn-rwo-1r"
  attic_storage_size: "500Gi"
  attic_requests_cpu: "500m"
  attic_requests_memory: "2Gi"
  attic_requests_ephemeral_storage: "1Gi"
  attic_limits_cpu: "4000m"
  attic_limits_memory: "8Gi"
  attic_limits_ephemeral_storage: "4Gi"
  attic_postgres_cluster_name: "attic-postgres"
  attic_postgres_image: "ghcr.io/cloudnative-pg/postgresql:18-system-trixie"
  attic_postgres_instances: "1"
  attic_postgres_db_name: "attic"
  attic_postgres_user: "attic"
  attic_postgres_storage_class_name: "longhorn-rwo-1r"
  attic_postgres_size: "20Gi"
  attic_postgres_requests_cpu: "250m"
  attic_postgres_requests_memory: "512Mi"
  attic_postgres_requests_ephemeral_storage: "1Gi"
  attic_postgres_limits_cpu: "2000m"
  attic_postgres_limits_memory: "2Gi"
  attic_postgres_limits_ephemeral_storage: "4Gi"
