apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  backrest_suspend: "true"
  backrest_image: "docker.io/garethgeorge/backrest:v1.14.1-alpine"
  backrest_storage_class: "longhorn-ssd-rwo-1r"
  backrest_state_size: "5Gi"
