apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix
resources:
  - element-web.yaml
  - persistent-volume-claims.yaml
  - postgres.yaml
  - synapse-db-integrity-repair.yaml
  - synapse.yaml
  - bridges.yaml
  - ingress.yaml
