apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: synapsedb
  namespace: matrix
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-system-trixie
  instances: 1
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
      prometheus.io/path: "/metrics"
  bootstrap:
    initdb:
      database: ${matrix_synapse_postgres_source_dbname:=synapse}
      owner: ${matrix_synapse_postgres_source_user:=synapse}
      secret:
        name: synapsedb-app
  managed:
    roles:
      - name: ${matrix_synapse_postgres_source_user:=synapse}
        ensure: present
        login: true
        passwordSecret:
          name: synapsedb-app
  storage:
    storageClass: ${matrix_postgres_storage_class_name}
    size: ${matrix_postgres_size}
  backup:
    barmanObjectStore:
      destinationPath: "s3://${matrix_postgres_backup_bucket}/${cluster_environment}/${matrix_synapsedb_backup_path:=synapsedb}/"
      endpointURL: "${matrix_postgres_backup_endpoint_url:=}"
      s3Credentials:
        accessKeyId:
          name: ${matrix_postgres_backup_credential_secret_name}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: ${matrix_postgres_backup_credential_secret_name}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  resources:
    requests:
      cpu: ${matrix_postgres_requests_cpu}
      memory: ${matrix_postgres_requests_memory}
    limits:
      cpu: ${matrix_postgres_limits_cpu}
      memory: ${matrix_postgres_limits_memory}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: whatsappdb
  namespace: matrix
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-system-trixie
  instances: 1
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
      prometheus.io/path: "/metrics"
  bootstrap:
    initdb:
      database: ${matrix_whatsapp_postgres_source_dbname:=mautrixwhatsapp}
      owner: ${matrix_whatsapp_postgres_source_user:=mautrixwhatsapp}
      secret:
        name: whatsappdb-app
  managed:
    roles:
      - name: ${matrix_whatsapp_postgres_source_user:=mautrixwhatsapp}
        ensure: present
        login: true
        passwordSecret:
          name: whatsappdb-app
  storage:
    storageClass: ${matrix_postgres_storage_class_name}
    size: ${matrix_postgres_size}
  backup:
    barmanObjectStore:
      destinationPath: "s3://${matrix_postgres_backup_bucket}/${cluster_environment}/whatsappdb/"
      endpointURL: "${matrix_postgres_backup_endpoint_url:=}"
      s3Credentials:
        accessKeyId:
          name: ${matrix_postgres_backup_credential_secret_name}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: ${matrix_postgres_backup_credential_secret_name}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  resources:
    requests:
      cpu: ${matrix_postgres_requests_cpu}
      memory: ${matrix_postgres_requests_memory}
    limits:
      cpu: ${matrix_postgres_limits_cpu}
      memory: ${matrix_postgres_limits_memory}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wadb
  namespace: matrix
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-system-trixie
  instances: 1
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
      prometheus.io/path: "/metrics"
  bootstrap:
    initdb:
      database: ${matrix_wa_postgres_source_dbname:=mautrixwhatsapp}
      owner: ${matrix_wa_postgres_source_user:=mautrixwhatsapp}
      secret:
        name: wadb-app
  managed:
    roles:
      - name: ${matrix_wa_postgres_source_user:=mautrixwhatsapp}
        ensure: present
        login: true
        passwordSecret:
          name: wadb-app
  storage:
    storageClass: ${matrix_postgres_storage_class_name}
    size: ${matrix_postgres_size}
  backup:
    barmanObjectStore:
      destinationPath: "s3://${matrix_postgres_backup_bucket}/${cluster_environment}/wadb/"
      endpointURL: "${matrix_postgres_backup_endpoint_url:=}"
      s3Credentials:
        accessKeyId:
          name: ${matrix_postgres_backup_credential_secret_name}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: ${matrix_postgres_backup_credential_secret_name}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  resources:
    requests:
      cpu: ${matrix_postgres_requests_cpu}
      memory: ${matrix_postgres_requests_memory}
    limits:
      cpu: ${matrix_postgres_limits_cpu}
      memory: ${matrix_postgres_limits_memory}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: telegramdb
  namespace: matrix
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-system-trixie
  instances: 1
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
      prometheus.io/path: "/metrics"
  bootstrap:
    initdb:
      database: ${matrix_telegram_postgres_source_dbname:=mautrixtelegram}
      owner: ${matrix_telegram_postgres_source_user:=mautrixtelegram}
      secret:
        name: telegramdb-app
  managed:
    roles:
      - name: ${matrix_telegram_postgres_source_user:=mautrixtelegram}
        ensure: present
        login: true
        passwordSecret:
          name: telegramdb-app
  storage:
    storageClass: ${matrix_postgres_storage_class_name}
    size: ${matrix_postgres_size}
  backup:
    barmanObjectStore:
      destinationPath: "s3://${matrix_postgres_backup_bucket}/${cluster_environment}/telegramdb/"
      endpointURL: "${matrix_postgres_backup_endpoint_url:=}"
      s3Credentials:
        accessKeyId:
          name: ${matrix_postgres_backup_credential_secret_name}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: ${matrix_postgres_backup_credential_secret_name}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  resources:
    requests:
      cpu: ${matrix_postgres_requests_cpu}
      memory: ${matrix_postgres_requests_memory}
    limits:
      cpu: ${matrix_postgres_limits_cpu}
      memory: ${matrix_postgres_limits_memory}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: signaldbprivate
  namespace: matrix
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-system-trixie
  instances: 1
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
      prometheus.io/path: "/metrics"
  bootstrap:
    initdb:
      database: ${matrix_signal_postgres_source_dbname:=mautrixsignal}
      owner: ${matrix_signal_postgres_source_user:=mautrixsignal}
      secret:
        name: signaldbprivate-app
  managed:
    roles:
      - name: ${matrix_signal_postgres_source_user:=mautrixsignal}
        ensure: present
        login: true
        passwordSecret:
          name: signaldbprivate-app
  storage:
    storageClass: ${matrix_postgres_storage_class_name}
    size: ${matrix_postgres_size}
  backup:
    barmanObjectStore:
      destinationPath: "s3://${matrix_postgres_backup_bucket}/${cluster_environment}/signaldbprivate/"
      endpointURL: "${matrix_postgres_backup_endpoint_url:=}"
      s3Credentials:
        accessKeyId:
          name: ${matrix_postgres_backup_credential_secret_name}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: ${matrix_postgres_backup_credential_secret_name}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  resources:
    requests:
      cpu: ${matrix_postgres_requests_cpu}
      memory: ${matrix_postgres_requests_memory}
    limits:
      cpu: ${matrix_postgres_limits_cpu}
      memory: ${matrix_postgres_limits_memory}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: synapsedb
  namespace: matrix
spec:
  schedule: "${matrix_postgres_backup_cron:=0 0 2 * * *}"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: synapsedb
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: whatsappdb
  namespace: matrix
spec:
  schedule: "${matrix_postgres_backup_cron:=0 0 2 * * *}"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: whatsappdb
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: wadb
  namespace: matrix
spec:
  schedule: "${matrix_postgres_backup_cron:=0 0 2 * * *}"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: wadb
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: telegramdb
  namespace: matrix
spec:
  schedule: "${matrix_postgres_backup_cron:=0 0 2 * * *}"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: telegramdb
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: signaldbprivate
  namespace: matrix
spec:
  schedule: "${matrix_postgres_backup_cron:=0 0 2 * * *}"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: signaldbprivate
