apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - scheduled-backup.yaml
  - backup-bucket-bootstrap.yaml
  - valkey.yaml
  - s3-bootstrap.yaml
  - stalwart.yaml
  - service.yaml
  - ingress.yaml
