apiVersion: v1
kind: Service
metadata:
  name: stalwart
  namespace: mail
spec:
  selector:
    app.kubernetes.io/name: stalwart
  ports:
    - { name: smtp, port: 25 }
    - { name: submission, port: 587 }
    - { name: submissions, port: 465 }
    - { name: imap, port: 143 }
    - { name: imaptls, port: 993 }
    - { name: sieve, port: 4190 }
    - { name: http, port: 8080 }
