apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 03ed4283-aa2e-4781-8236-fd69a38e130a
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - hostname: "*.h4xx.io"
        service: https://traefik.traefik.svc.cluster.local:443
      - service: http_status:404
