apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  valkey_auth_secret_name: "nextcloud-valkey"
  valkey_min_replicas_to_write: "1"
  valkey_persistence_size: "8Gi"
  valkey_replica_count: "2"
  valkey_storage_class_name: "ssd-cephfs-2r"
