apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  namespace: flux-system
data:
  pretix_suspend: "true"
  cloudflare_tunnel_hostname: ""
  pretix_alias_host: "tickets"
  pretix_data_size: "5Gi"
  pretix_data_storage_class_name: "longhorn-ssd-rwo-1r"
  pretix_image_tag: "2026.8.0"
  pretix_instance_name: "h4xx Tickets"
  pretix_limits_memory: "2Gi"
  pretix_mail_from: "tickets@h4xx.io"
  pretix_postgres_backup_bucket: "pretix-postgres-backup"
  pretix_postgres_backup_credential_secret_name: "pretix-postgres-backup-credentials"
  pretix_postgres_backup_cron: "0 45 3 * * *"
  pretix_postgres_backup_endpoint_url: ""
  pretix_postgres_backup_generation: ""
  pretix_postgres_backup_retention: "30d"
  pretix_postgres_backup_server_name: "pretix-postgres"
  pretix_postgres_instances: "1"
  pretix_postgres_limits_memory: "1Gi"
  pretix_postgres_requests_cpu: "50m"
  pretix_postgres_requests_memory: "256Mi"
  pretix_postgres_size: "8Gi"
  pretix_postgres_storage_class_name: "longhorn-nvme-rwo-2r"
  pretix_primary_host: "pretix"
  pretix_redis_size: "1Gi"
  pretix_redis_storage_class_name: "longhorn-ssd-rwo-1r"
  pretix_requests_cpu: "100m"
  pretix_requests_memory: "512Mi"
  pretix_task_concurrency: "2"
  pretix_task_limits_memory: "1536Mi"
  pretix_task_requests_cpu: "50m"
  pretix_task_requests_memory: "256Mi"
  pretix_valkey_image_tag: "9.1.2-alpine"
  pretix_web_workers: "3"
