apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../immich
patches:
  - target:
      version: v1
      kind: Service
      name: immich-postgres-source
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: immich-postgres-source
        namespace: immich
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: immich-postgres
    patch: |-
      - op: remove
        path: /spec/bootstrap/initdb/import
      - op: remove
        path: /spec/externalClusters
