apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - service.yaml
  - bootstrap-job.yaml
  - ingress.yaml
