apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${attic_postgres_cluster_name}
  namespace: ${attic_namespace}
spec:
  imageName: ${attic_postgres_image}
  instances: ${attic_postgres_instances}
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
      prometheus.io/path: /metrics
  bootstrap:
    initdb:
      database: ${attic_postgres_db_name}
      owner: ${attic_postgres_user}
  storage:
    storageClass: ${attic_postgres_storage_class_name}
    size: ${attic_postgres_size}
  backup:
    barmanObjectStore:
      destinationPath: "s3://${attic_postgres_backup_bucket}/${cluster_environment}/attic-postgres/"
      endpointURL: "${attic_postgres_backup_endpoint_url:=}"
      s3Credentials:
        accessKeyId:
          name: ${attic_postgres_backup_credential_secret_name}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: ${attic_postgres_backup_credential_secret_name}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "${attic_postgres_backup_retention:=30d}"
  resources:
    requests:
      cpu: ${attic_postgres_requests_cpu}
      memory: ${attic_postgres_requests_memory}
      ephemeral-storage: ${attic_postgres_requests_ephemeral_storage}
    limits:
      cpu: ${attic_postgres_limits_cpu}
      memory: ${attic_postgres_limits_memory}
      ephemeral-storage: ${attic_postgres_limits_ephemeral_storage}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: ${attic_postgres_cluster_name}
  namespace: ${attic_namespace}
spec:
  schedule: "${attic_postgres_backup_cron:=0 0 2 * * *}"
  backupOwnerReference: self
  immediate: true
  cluster:
    name: ${attic_postgres_cluster_name}
